#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vehicle_parking_system
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="parkingmanagement")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void Inserttbl_slot(tbl_slot instance);
    partial void Updatetbl_slot(tbl_slot instance);
    partial void Deletetbl_slot(tbl_slot instance);
    partial void Inserttblarrival(tblarrival instance);
    partial void Updatetblarrival(tblarrival instance);
    partial void Deletetblarrival(tblarrival instance);
    partial void Inserttbldeparture(tbldeparture instance);
    partial void Updatetbldeparture(tbldeparture instance);
    partial void Deletetbldeparture(tbldeparture instance);
    partial void Insertcar(car instance);
    partial void Updatecar(car instance);
    partial void Deletecar(car instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::vehicle_parking_system.Properties.Settings.Default.parkingmanagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<tbl_slot> tbl_slots
		{
			get
			{
				return this.GetTable<tbl_slot>();
			}
		}
		
		public System.Data.Linq.Table<tblarrival> tblarrivals
		{
			get
			{
				return this.GetTable<tblarrival>();
			}
		}
		
		public System.Data.Linq.Table<tbldeparture> tbldepartures
		{
			get
			{
				return this.GetTable<tbldeparture>();
			}
		}
		
		public System.Data.Linq.Table<car> cars
		{
			get
			{
				return this.GetTable<car>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_slots")]
	public partial class tbl_slot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Slot_No;
		
		private string _Location;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSlot_NoChanging(string value);
    partial void OnSlot_NoChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    #endregion
		
		public tbl_slot()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slot_No", DbType="NVarChar(50)")]
		public string Slot_No
		{
			get
			{
				return this._Slot_No;
			}
			set
			{
				if ((this._Slot_No != value))
				{
					this.OnSlot_NoChanging(value);
					this.SendPropertyChanging();
					this._Slot_No = value;
					this.SendPropertyChanged("Slot_No");
					this.OnSlot_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblarrival")]
	public partial class tblarrival : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _driver_name;
		
		private string _car_no;
		
		private string _stay_time;
		
		private string _selected_slot;
		
		private string _category;
		
		private System.Nullable<System.DateTime> _a_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Ondriver_nameChanging(string value);
    partial void Ondriver_nameChanged();
    partial void Oncar_noChanging(string value);
    partial void Oncar_noChanged();
    partial void Onstay_timeChanging(string value);
    partial void Onstay_timeChanged();
    partial void Onselected_slotChanging(string value);
    partial void Onselected_slotChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void Ona_timeChanging(System.Nullable<System.DateTime> value);
    partial void Ona_timeChanged();
    #endregion
		
		public tblarrival()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[driver name]", Storage="_driver_name", DbType="NVarChar(30)")]
		public string driver_name
		{
			get
			{
				return this._driver_name;
			}
			set
			{
				if ((this._driver_name != value))
				{
					this.Ondriver_nameChanging(value);
					this.SendPropertyChanging();
					this._driver_name = value;
					this.SendPropertyChanged("driver_name");
					this.Ondriver_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_no", DbType="NVarChar(30)")]
		public string car_no
		{
			get
			{
				return this._car_no;
			}
			set
			{
				if ((this._car_no != value))
				{
					this.Oncar_noChanging(value);
					this.SendPropertyChanging();
					this._car_no = value;
					this.SendPropertyChanged("car_no");
					this.Oncar_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stay_time", DbType="NVarChar(50)")]
		public string stay_time
		{
			get
			{
				return this._stay_time;
			}
			set
			{
				if ((this._stay_time != value))
				{
					this.Onstay_timeChanging(value);
					this.SendPropertyChanging();
					this._stay_time = value;
					this.SendPropertyChanged("stay_time");
					this.Onstay_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selected_slot", DbType="NVarChar(50)")]
		public string selected_slot
		{
			get
			{
				return this._selected_slot;
			}
			set
			{
				if ((this._selected_slot != value))
				{
					this.Onselected_slotChanging(value);
					this.SendPropertyChanging();
					this._selected_slot = value;
					this.SendPropertyChanged("selected_slot");
					this.Onselected_slotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> a_time
		{
			get
			{
				return this._a_time;
			}
			set
			{
				if ((this._a_time != value))
				{
					this.Ona_timeChanging(value);
					this.SendPropertyChanging();
					this._a_time = value;
					this.SendPropertyChanged("a_time");
					this.Ona_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbldeparture")]
	public partial class tbldeparture : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _carno;
		
		private string _driver;
		
		private string _type;
		
		private string _p_type;
		
		private System.Nullable<decimal> _amoount;
		
		private System.Nullable<System.DateTime> _departure_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OncarnoChanging(string value);
    partial void OncarnoChanged();
    partial void OndriverChanging(string value);
    partial void OndriverChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Onp_typeChanging(string value);
    partial void Onp_typeChanged();
    partial void OnamoountChanging(System.Nullable<decimal> value);
    partial void OnamoountChanged();
    partial void Ondeparture_timeChanging(System.Nullable<System.DateTime> value);
    partial void Ondeparture_timeChanged();
    #endregion
		
		public tbldeparture()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carno", DbType="NVarChar(50)")]
		public string carno
		{
			get
			{
				return this._carno;
			}
			set
			{
				if ((this._carno != value))
				{
					this.OncarnoChanging(value);
					this.SendPropertyChanging();
					this._carno = value;
					this.SendPropertyChanged("carno");
					this.OncarnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driver", DbType="NVarChar(50)")]
		public string driver
		{
			get
			{
				return this._driver;
			}
			set
			{
				if ((this._driver != value))
				{
					this.OndriverChanging(value);
					this.SendPropertyChanging();
					this._driver = value;
					this.SendPropertyChanged("driver");
					this.OndriverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_type", DbType="NVarChar(50)")]
		public string p_type
		{
			get
			{
				return this._p_type;
			}
			set
			{
				if ((this._p_type != value))
				{
					this.Onp_typeChanging(value);
					this.SendPropertyChanging();
					this._p_type = value;
					this.SendPropertyChanged("p_type");
					this.Onp_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amoount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> amoount
		{
			get
			{
				return this._amoount;
			}
			set
			{
				if ((this._amoount != value))
				{
					this.OnamoountChanging(value);
					this.SendPropertyChanging();
					this._amoount = value;
					this.SendPropertyChanged("amoount");
					this.OnamoountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> departure_time
		{
			get
			{
				return this._departure_time;
			}
			set
			{
				if ((this._departure_time != value))
				{
					this.Ondeparture_timeChanging(value);
					this.SendPropertyChanging();
					this._departure_time = value;
					this.SendPropertyChanged("departure_time");
					this.Ondeparture_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.car")]
	public partial class car : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _drivername;
		
		private string _car_no;
		
		private string _stay_time;
		
		private string _selected_slot;
		
		private string _category;
		
		private System.Nullable<System.DateTime> _a_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndrivernameChanging(string value);
    partial void OndrivernameChanged();
    partial void Oncar_noChanging(string value);
    partial void Oncar_noChanged();
    partial void Onstay_timeChanging(string value);
    partial void Onstay_timeChanged();
    partial void Onselected_slotChanging(string value);
    partial void Onselected_slotChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void Ona_timeChanging(System.Nullable<System.DateTime> value);
    partial void Ona_timeChanged();
    #endregion
		
		public car()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_drivername", DbType="NVarChar(50)")]
		public string drivername
		{
			get
			{
				return this._drivername;
			}
			set
			{
				if ((this._drivername != value))
				{
					this.OndrivernameChanging(value);
					this.SendPropertyChanging();
					this._drivername = value;
					this.SendPropertyChanged("drivername");
					this.OndrivernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_no", DbType="NVarChar(50)")]
		public string car_no
		{
			get
			{
				return this._car_no;
			}
			set
			{
				if ((this._car_no != value))
				{
					this.Oncar_noChanging(value);
					this.SendPropertyChanging();
					this._car_no = value;
					this.SendPropertyChanged("car_no");
					this.Oncar_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stay_time", DbType="NVarChar(50)")]
		public string stay_time
		{
			get
			{
				return this._stay_time;
			}
			set
			{
				if ((this._stay_time != value))
				{
					this.Onstay_timeChanging(value);
					this.SendPropertyChanging();
					this._stay_time = value;
					this.SendPropertyChanged("stay_time");
					this.Onstay_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selected_slot", DbType="NVarChar(50)")]
		public string selected_slot
		{
			get
			{
				return this._selected_slot;
			}
			set
			{
				if ((this._selected_slot != value))
				{
					this.Onselected_slotChanging(value);
					this.SendPropertyChanging();
					this._selected_slot = value;
					this.SendPropertyChanged("selected_slot");
					this.Onselected_slotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> a_time
		{
			get
			{
				return this._a_time;
			}
			set
			{
				if ((this._a_time != value))
				{
					this.Ona_timeChanging(value);
					this.SendPropertyChanging();
					this._a_time = value;
					this.SendPropertyChanged("a_time");
					this.Ona_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
